services:
  - type: web
    name: gescoches
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn gescoches.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: gescoches-db
          property: connectionString

databases:
  - name: gescoches-db
    databaseName: gescoches_db
    user: gescoches_user
    region: ohio
    plan: free
